version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 103.108.140.128
      MYSQL_USER: test
      MYSQL_PASSWORD: test12!
      MYSQL_DATABASE: todo
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test12!
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

